### ISSUE TITLE
Syba CM119 GPO connection detail

### ISSUE THREAD

**Issue by TedBusto** [wb2osz/direwolf-doc#5]
In Radio-Interface-Guide.pdf you mention that you connect a wire with a resistor and transistor to the ground and a GPIO pin on the Syba and you provide two pictures.

Can you please explain in more detail? Which Transistor and Resistor? Which pin do you solder it to? I can't quite make it out from the photo.

**Comment by dranch** [comment]
Here is one example showing the transistor and resistor type and values: http://www.dunmire.org/projects/DigitalCommCenter/soundmodem/mySoundCardInterface.png

**Comment by wb2osz** [comment]
The schematic is for a Kenwork (sic) HT.  That doesn't help someone with a Kenwood HT.  :-)

**Comment by wb2osz** [comment]
The schematic David provided is for using the RS-232 RTS control signal.  This could be + or -12 volts.   The diode is very important so the transistor base does not go very much negative.  I blew out a few transistors (very very long time ago) before understanding that.

You are talking about the GPIO pin on the CM108 or CM119 chip which can only vary between 0 and 5 volts.  The diode would not be necessary in this case.

to be continued...  soon.

**Comment by wb2osz** [comment]
Pin 13.
Look in section 7.5 of the radio interface guide.  It has some specific examples.
Around 10k (not critical) and any general purpose NPN transistor would be fine.  2N2222, 2N3904, etc.
•	http://www.qsl.net/kb9mwr/projects/voip/usbfob-119.pdf 
•	http://rtpdir.weebly.com/uploads/1/6/8/7/1687703/usbfob.pdf 
•	http://www.repeater-builder.com/projects/fob/USB-Fob-Construction.pdf 

Does this help?
73,
John WB2OSZ

**Comment by dranch** [comment]
I posted that link as I've used that circuit on many Raspberry Pis with 3.3v low current GPIO pins running for years.  I assumed here that the GPIO pin on a CM108 would work similar.  Beyond that, yes.. this schematic is specifically for Kenwood-style "dual prong" cables so it's up to the reader to translate it to whatever radio they have.

**Comment by TedBusto** [comment]
> Pin 13. Look in section 7.5 of the radio interface guide. It has some specific examples. Around 10k (not critical) and any general purpose NPN transistor would be fine. 2N2222, 2N3904, etc. • http://www.qsl.net/kb9mwr/projects/voip/usbfob-119.pdf • http://rtpdir.weebly.com/uploads/1/6/8/7/1687703/usbfob.pdf • http://www.repeater-builder.com/projects/fob/USB-Fob-Construction.pdf
> 
> Does this help? 73, John WB2OSZ

Yes this is very helpful. I think I am almost there.

Is this pin 13?
![IMG20241107162546](https://github.com/user-attachments/assets/9007f7a9-7e70-4673-a0af-7cb03251e09b)

The other side in case you want to check for other issues.
![IMG20241107163207](https://github.com/user-attachments/assets/576b3f6c-c173-421c-9187-ed7a67f9a590)

**Comment by TedBusto** [comment]
and a close-up of my soldering job if needed.

![IMG20241107162659](https://github.com/user-attachments/assets/c07565a2-ebc7-4ad6-aa69-0d1d85bb7881)

**Comment by wb2osz** [comment]
The circle in the chip and arrow on the board indicate pin 1.  Count counter clockwise when viewing from the top.

![image](https://github.com/user-attachments/assets/55048084-2920-448b-a2f9-6fedab0be714)

I need to fix the documentation to be clearer.  

I stuck a piece of insulated wire under pins 24 through 13 for physical stability.  The bare end was bent up and soldered to pin 13.   

Is that a 10k resistor?  It looks like 1k to me.

What is the transistor type?  I would like to double check the pin out.

**Comment by dranch** [comment]
There are lots of guides out there on the Internet on how to do this mod.  Google "CM119 GPIO pin for allstar" and you'll get many hits on detailed guides like http://squirrelengineering.com/ham-radio/build-a-portable-allstar-link-hotspot-part-3-sound-card-fob-mods/

**Comment by TedBusto** [comment]
> The circle in the chip and arrow on the board indicate pin 1. Count counter clockwise when viewing from the top.
> 
> ![image](https://private-user-images.githubusercontent.com/6499991/384160533-55048084-2920-448b-a2f9-6fedab0be714.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMjExNzUsIm5iZiI6MTczMTAyMDg3NSwicGF0aCI6Ii82NDk5OTkxLzM4NDE2MDUzMy01NTA0ODA4NC0yOTIwLTQ0OGItYTJmOS02ZmVkYWIwYmU3MTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDdUMjMwNzU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjA4ZDkwYWNmOWNhYTAxN2Q4NDFlY2E3ODNmZmQ0ZTk0YzZhZmM4ZDYzMDcyNDg0Mzc0MmQyZDQzNTk5ZDVkMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.MQctrt35bzndZFcL6Je_MMonmd-ntufBFSssOnC2S4c)
> 
> I need to fix the documentation to be clearer.
> 
> I stuck a piece of insulated wire under pins 24 through 13 for physical stability. The bare end was bent up and soldered to pin 13.
> 
> Is that a 10k resistor? It looks like 1k to me.
> 
> What is the transistor type? I would like to double check the pin out.

Excellent. Thank you so much. Would you like me to take some high quality photos for the documentation?
